# Generated by Django 4.1.6 on 2024-06-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistical',
            name='buyed_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistical',
            name='cancelled_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistical',
            name='pending_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistical',
            name='profit_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistical',
            name='returned_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistical',
            name='revenue_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistical',
            name='ship_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistical',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
