# Generated by Django 4.1.6 on 2024-06-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistical', '0002_alter_statistical_buyed_total_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statistical',
            table='statiscal',
        ),
    ]
