# Generated by Django 4.1.6 on 2024-06-11 15:07

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statistical', '0003_alter_statistical_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.BigIntegerField(default=0)),
                ('buyed_total', models.BigIntegerField(default=0)),
                ('ship_total', models.BigIntegerField(default=0)),
                ('pending_total', models.BigIntegerField(default=0)),
                ('cancelled_total', models.BigIntegerField(default=0)),
                ('returned_total', models.BigIntegerField(default=0)),
                ('revenue_total', models.BigIntegerField(default=0)),
                ('profit_total', models.BigIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('close', 'close')], default='pending', max_length=10)),
            ],
            options={
                'db_table': 'campaign',
            },
        ),
    ]
