# Generated by Django 4.1.6 on 2024-06-11 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical', '0004_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='discount',
            field=models.IntegerField(default=0, help_text='Enter a value from 0 to 100 to set the discount percentage.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
