# Generated by Django 4.1.6 on 2024-11-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical', '0005_alter_campaign_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='discount_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
