# Generated by Django 4.1.6 on 2024-11-03 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_remove_order_user_order_customer'),
        ('statistical', '0006_campaign_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='CampaignOrder', to='product.order'),
        ),
        migrations.CreateModel(
            name='CampaignOrder',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical.campaign')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order')),
            ],
            options={
                'db_table': 'campaign_order',
            },
        ),
    ]
