# Generated by Django 4.1.6 on 2024-11-03 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_address_warehouse_product_warehouse'),
        ('statistical', '0007_campaign_orders_campaignorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('flash_deal', 'Flash Deal'), ('product_discount', 'Product Discount')], max_length=255)),
                ('discount', models.IntegerField(default=0, help_text='Enter a value from 0 to 100 to set the discount percentage.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_code', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'promotion',
            },
        ),
        migrations.CreateModel(
            name='CampaignPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical.campaign')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical.promotion')),
            ],
            options={
                'db_table': 'campaign_promotion',
            },
        ),
        migrations.AddField(
            model_name='campaignorder',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='CampaignPromotion', to='statistical.promotion'),
        ),
    ]
