version: "3.1"

services:
  db:
    image: postgres:16
    # restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    # restart: always
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20
