# Generated by Django 4.1.6 on 2024-04-12 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='static/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
