# Generated by Django 4.1.6 on 2024-06-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
