# Generated by Django 4.1.6 on 2024-04-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
