# Generated by Django 4.1.6 on 2024-04-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customer_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='selected_total',
        ),
    ]
