# Generated by Django 4.1.6 on 2024-04-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customer_selected_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='money_total',
        ),
        migrations.AddField(
            model_name='customer',
            name='profit_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='revenue_total',
            field=models.IntegerField(default=0),
        ),
    ]
