# Generated by Django 4.1.6 on 2024-05-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_customer_money_total_customer_profit_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
    ]
