# Generated by Django 4.1.6 on 2024-06-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pending_total',
            field=models.IntegerField(default=0),
        ),
    ]
