# Generated by Django 4.1.6 on 2024-12-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_notificationcontent_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(default=0)),
                ('buyed_total', models.BigIntegerField(default=0)),
                ('cancelled_total', models.BigIntegerField(default=0)),
                ('returned_total', models.BigIntegerField(default=0)),
                ('pending_total', models.BigIntegerField(default=0)),
                ('ship_total', models.BigIntegerField(default=0)),
                ('revenue_total', models.BigIntegerField(default=0)),
                ('profit_total', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'statiscal',
            },
        ),
    ]
