# Generated by Django 4.1.6 on 2024-04-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customer_total'),
        ('product', '0003_comment_remove_product_rating_product_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='Rating', to='user.customer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='Comment', to='user.customer'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
