# Generated by Django 4.1.6 on 2024-04-13 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_ratings_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('buyed_total', models.IntegerField(default=0)),
                ('ship_total', models.IntegerField(default=0)),
                ('selected_total', models.IntegerField(default=0)),
                ('cancelled_total', models.IntegerField(default=0)),
                ('returned_total', models.IntegerField(default=0)),
                ('money_total', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
