# Generated by Django 4.1.6 on 2024-04-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_cart_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
