# Generated by Django 4.1.6 on 2024-04-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_agency_selected_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='money_total',
            new_name='profit_total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='money_total',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='money_total',
        ),
        migrations.AddField(
            model_name='agency',
            name='revenue_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='revenue_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productitem',
            name='profit_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productitem',
            name='revenue_total',
            field=models.IntegerField(default=0),
        ),
    ]
