# Generated by Django 4.1.6 on 2024-05-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_cart_productitem_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('creating', 'Creating'), ('ship', 'Ship'), ('cancel', 'Cancel'), ('complete', 'Complete'), ('return', 'Return'), ('pending', 'Pending')], default='ship', max_length=10),
        ),
    ]
