# Generated by Django 4.1.6 on 2024-06-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='pending_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='pending_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productitem',
            name='pending_total',
            field=models.IntegerField(default=0),
        ),
    ]
