# Generated by Django 4.1.6 on 2024-06-09 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_comment_images_remove_comment_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ratings',
        ),
        # migrations.RemoveField(
        #     model_name='rating',
        #     name='product',
        # ),
        migrations.AddField(
            model_name='rating',
            name='order_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.orderproduct'),
        ),
    ]
