# Generated by Django 4.1.6 on 2024-06-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_product_comments_remove_product_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate_point',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
