# Generated by Django 4.1.6 on 2024-06-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_rating_rate_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
