# Generated by Django 4.1.6 on 2024-06-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_rating_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='content',
            new_name='comment',
        ),
    ]
