# Generated by Django 4.1.6 on 2024-06-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_rename_rating_review'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
