# Generated by Django 4.1.6 on 2024-11-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_remove_order_user_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='customer',
        ),
    ]
