# Generated by Django 4.1.6 on 2024-04-13 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('buyed_total', models.IntegerField(default=0)),
                ('ship_total', models.IntegerField(default=0)),
                ('selected_total', models.IntegerField(default=0)),
                ('cancelled_total', models.IntegerField(default=0)),
                ('returned_total', models.IntegerField(default=0)),
                ('money_total', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('buyed_total', models.IntegerField(default=0)),
                ('ship_total', models.IntegerField(default=0)),
                ('selected_total', models.IntegerField(default=0)),
                ('cancelled_total', models.IntegerField(default=0)),
                ('returned_total', models.IntegerField(default=0)),
                ('money_total', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('rating', models.FloatField(default=0)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.agency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
