# Generated by Django 4.1.6 on 2024-04-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productimage_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='selected_total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selected_total',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='selected_total',
        ),
    ]
