# Generated by Django 4.1.6 on 2024-05-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_discount_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
