# Generated by Django 4.1.6 on 2024-06-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_agency_buyed_total_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentImage',
        ),
    ]
