# Generated by Django 4.1.6 on 2024-06-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_delete_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
