# Generated by Django 4.1.6 on 2024-06-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_review_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agency',
            table='agency',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderproduct',
            table='order_product',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_image',
        ),
        migrations.AlterModelTable(
            name='productitem',
            table='product_item',
        ),
    ]
